blueprint:
    name: icn
    layers:
        - os
        - k8s

    os: &os
        -
            name: lynis
            what: lynis
            optional: "False"
        -
            name: vuls
            what: vuls
            optional: "False"

    k8s: &k8s
        -
            name: conformance
            what: conformance
            optional: "False"
        -
            name: kube-hunter
            what: kube-hunter
            optional: "False"
